### ISSUE TITLE
Trying to follow "Basic Usage - Base16 example" fails...

### ISSUE THREAD

**Issue by s-n-g** [richardneililagan/base16-builder-node#12]
Hi all

I'm trying to follow the instructions under [Basic Usage - Base16 example](https://github.com/base16-project/base16-builder-node#basic-usage---base16-example) for base16-pyradio

A `cd ../..` should be added before the last command...

Then
```
╭─spiros@py ~  
╰─➤  mkdir working_dir && cd working_dir
╭─spiros@py ~/working_dir  
╰─➤  mkdir -p base16/templates && cd base16
╭─spiros@py ~/working_dir/base16  
╰─➤  git clone https://github.com/base16-project/base16-schemes.git schemes
Cloning into 'schemes'...
remote: Enumerating objects: 275, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 275 (delta 35), reused 246 (delta 24), pack-reused 0
Receiving objects: 100% (275/275), 64.29 KiB | 877.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.
╭─spiros@py ~/working_dir/base16  
╰─➤  cd templates
╭─spiros@py ~/working_dir/base16/templates  
╰─➤  git clone https://github.com/edunfelt/base16-pyradio.git
Cloning into 'base16-pyradio'...
remote: Enumerating objects: 1012, done.
remote: Counting objects: 100% (1012/1012), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 1012 (delta 961), reused 961 (delta 927), pack-reused 0
Receiving objects: 100% (1012/1012), 227.07 KiB | 1.30 MiB/s, done.
Resolving deltas: 100% (961/961), done.
╭─spiros@py ~/working_dir/base16/templates  
╰─➤  cd ../..
╭─spiros@py ~/working_dir  
╰─➤  base16 build base16 --prefix base16-
Parsing scheme definitions...
232 schemes found.
Parsing template definitions...
file:///usr/lib/node_modules/base16-builder-node/lib/template.class.js:82
          if (prefix === undefined) prefix = DEFAULT_PREFIX;
                                    ^

ReferenceError: DEFAULT_PREFIX is not defined
    at file:///usr/lib/node_modules/base16-builder-node/lib/template.class.js:82:37
    at Array.map (<anonymous>)
    at file:///usr/lib/node_modules/base16-builder-node/lib/template.class.js:78:47
    at Array.reduce (<anonymous>)
    at file:///usr/lib/node_modules/base16-builder-node/lib/template.class.js:68:55
    at new Promise (<anonymous>)
    at Function.populate (file:///usr/lib/node_modules/base16-builder-node/lib/template.class.js:60:12)
    at Object.builder.build (file:///usr/lib/node_modules/base16-builder-node/lib/builder.js:15:14)
    at Command.<anonymous> (file:///usr/lib/node_modules/base16-builder-node/lib/app.js:26:23)
    at Command.listener [as _actionHandler] (/usr/lib/node_modules/base16-builder-node/node_modules/commander/lib/command.js:482:17)
```

`base16-builder-node` has just been installed with

```
sudo npm -g base16-builder-node
```

Am I doing something wrong here?

**Comment by joshgoebel** [comment]
Ah.  Bug. Use --prefix though like in readme and it should work.

**Comment by joshgoebel** [comment]
Install 1.2 please.

**Comment by s-n-g** [comment]
Where do I get version 1.2?

`npm update` is still on `1.1`

**Comment by joshgoebel** [comment]
NPM sometimes lags.  I just pushed v1.2.1 to fix this issue.  The problem was I had `prefix` defined in my template config so I was never seeing the error, whether I passed it or not.

**Comment by s-n-g** [comment]
All done!
Thank you!

It took me so long to reply, because `base16 -V` still gives `1.1.0`

I will add a PR for the documentation...
